services:
  keycloak:
    build: 
      context: . 
      dockerfile: Dockerfile-keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_PROFILE_FEATURE_TOKEN_EXCHANGE=enabled 
      - KEYCLOAK_PROFILE_FEATURE_ADMIN_FINE_GRAINED_AUTHZ=enabled 
      - KEYCLOAK_PROFILE_FEATURE_ADMIN_FINE_GRAINED_AUTHZ=enabled 
    volumes:
      - ./keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data: